apiVersion: v1
kind: Service
metadata:
  name: k8s-api-gateway-nodeport
spec:
  type: NodePort # default는 ClusterIp : 서비스
  selector:
    app: k8s-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080